### ISSUE TITLE
Download only latest?

### ISSUE THREAD

**Issue by CyrosX** [heeplr/document-dl#1]
Is it possible to only download the latest invoice? (
E.g. a o2 cronjob, running every month.

**Comment by heeplr** [comment]
There is no way to get the latest document per se but there are a few possible approaches to achieve that:

For o2, the latest document should always be the first one (**id** = 0), so
```bash
$ document-dl --action download --jq 'contains({id: 0})' o2
```
will download the latest invoice. But this behaviour might change in the future and other plugins might behave differently as well, so you might not detect when it breaks if you leave the cronjob completely unsupervised.

If you know the date of the previous invoice, you could also filter for all documents newer than that. 
E.g. if the current invoice has **date** = 2021-07-01, then outputting any invoice newer than that will yield the latest one:
```
$ document-dl --action download --jq 'select(.date > "2021-07-01T")' --jq 'contains({"doctype":"BILL"})' o2
```

All plugins should add the **unread** attribute which can be used to filter for new documents:

```
$ document-dl --jq 'contains({"unread": true})' --action download ...
```
Although not all plugins do (yet).


EDIT: made clear that filtering by "unread=true" would be the way to go.
